name: Build Windows executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Git tags manually
        run: git fetch --prune --unshallow --tags
      - name: Set up latest Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch pyinstaller
          git describe --tags
          python -m pip install -vvv .

      - name: Compose build version label
        id: version
        shell: bash
        run: |
          echo "VERSION_LABEL=$(ytpb --version)" >> $GITHUB_OUTPUT

      - name: Build Windows executable binary
        run: >
          python -m PyInstaller --onefile
          --name "ytpb-${{ steps.version.outputs.VERSION_LABEL }}.exe"
          src/ytpb/__main__.py

      - name: Simple and quick check
        run: dist/ytpb-${{ steps.version.outputs.VERSION_LABEL }}.exe --version

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        with:
          name: ytpb-windows
          path: dist/ytpb-*.exe
          retention-days: 3
