name: Build Windows executable

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    outputs:
      binary-url: ${{ steps.upload.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Git tags manually
        run: git fetch --prune --unshallow --tags

      - name: Set up latest Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install hatch pyinstaller
          python -m pip install .

      - name: Compose build version label
        id: version
        shell: bash
        run: echo "VERSION=$(python -m hatch version)" >> $GITHUB_OUTPUT

      - name: Build Windows executable binary
        run: >
          python -m PyInstaller --noconsole --onefile
          --name "ytpb-${{ steps.version.outputs.VERSION }}"
          src/ytpb/__main__.py

      - name: Simple and quick check
        run: dist/ytpb-${{ steps.version.outputs.VERSION }}.exe --version

      - name: Upload built binary as artifact
        uses: actions/upload-artifact@v4
        id: upload
        with:
          name: ytpb-windows
          path: dist/ytpb-*.exe
          retention-days: 3
