name: Windows tests preparation

on:
  workflow_dispatch:

env:
  python-version: 3.11

jobs:
  prepare:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4
    - name: Set up FFmpeg
      uses: FedericoCarboni/setup-ffmpeg@v3
      with:
        ffmpeg-version: release
        architecture: ""
        github-token: ${{ github.server_url == 'https://github.com' && github.token || '' }}
    - name: Set up Python ${{ env.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install .[test]
    - name: Save test pattern files
      run: |
        python -m pytest tests --pm-save-patterns || true
    - name: Create pull request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: auto/pre-windows-tests
        delete-branch: true
        commit-message: "test(windows): Create new test pattern files for Windows"
        labels: github
        title: "auto: Add new test pattern files for Windows"
        body: |
          Automatically created by the `pre-windows-tests` GitHub Action.
